name: Soul Flour Bakery
favicon: null
layout_spectrum: 0.82426
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090000'
    - '#8a0a15'
    - '#e5ac5d'
    - '#a54212'
    - '#fefaf6'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
