typography_spectrum: 0.60043
color:
  brandColors:
    - '#cecec4'
    - '#b6b5a9'
    - '#89887c'
    - '#302e2f'
    - '#4c4b47'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.74121
analytics:
  google: null
  facebook: null
  twitter: null
name: Soul Flour Bakery
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ROAMING HEARTH PIZZA
purpose: []
