name: Soul Flour Bakery
favicon: null
layout_spectrum: 0.27148
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cecec4'
    - '#b6b5a9'
    - '#89887c'
    - '#302e2f'
    - '#4c4b47'
  brandStrength: 1
  lightness: 1
  saturation: 0.0625
  rhythmicContrast: 1
purpose: []
