name: Soul Flour Bakery
favicon: null
layout_spectrum: 0.49244
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171c1c'
    - '#9393a3'
    - '#f4461e'
    - '#f7b828'
    - '#e0e0ec'
  brandStrength: 0.30407111113891006
  lightness: 0.1787304801400751
  saturation: 0.9485665403772146
  rhythmicContrast: 0.13461965695023537
purpose: []
