name: Soul Flour Bakery
favicon: null
layout_spectrum: 1
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171c1c'
    - '#9393a3'
    - '#f4461e'
    - '#f7b828'
    - '#e0e0ec'
  brandStrength: 0.5
  lightness: 1
  saturation: 0
  rhythmicContrast: 0
purpose: []
