name: Soul Flour Bakery
favicon: null
layout_spectrum: 0.50981
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#cccec9'
    - '#141510'
    - '#8c918d'
    - '#655f4c'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
