name: Soul Flour Bakery
favicon: null
layout_spectrum: 0.50981
typography_spectrum: 0.60043
title: 'SOUL FLOUR BAKERY & ROAMING HEARTH PIZZA'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#dfdfdf'
    - '#979797'
    - '#565656'
    - '#111111'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
